<a href="https://colab.research.google.com/github/Hozaifabinumair2011/Vscode/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
data_type = [('name','S15'),('class',int),('height',float)]
students_details = [('James',5,48.5),('Nail',6,52.5),('Paul',5,42.5),('Pit',5,40.11)]
#Create a structured array
students = np.array(students_details, dtype=data_type)
print("Original array:")
print(students)
print("Sortb by height")
print(np.sort(students, order='height'))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.5 )
 (b'Pit', 5, 40.11)]
Sortb by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.5 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [6]:
a = np.arange(9,dtype=np.float64).reshape(3,3)
print('First array;')
print(a)
print('\n')

b = np.array([10,10,10])
print('Second array:')
print(b)
print('\n')

print('Add the two arrays:')
print(np.add(a,b))
print('\n')

print('Subtract the two arrays;')
print(np.subtract(a,b))
print('\n')

print('Multiply the two arrays:')
print(np.multiply(a,b))
print('\n')

print('Divivde the two arrays:')
print(np.divide(a,b))
print('\n')

First array;
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays;
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divivde the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


